### ISSUE TITLE
No success or error callbacks for request permissions

### ISSUE THREAD

**Issue by stephenrob** [lulibrary/Background-Beacon-Monitoring#2]
There is no callback fired for the requestPermissions method.

Currently the method definition is as follows:

```
cordova.requestPermissions(this, 0, PERMISSIONS);
```

This should use the status of requesting permissions to fire the correct callback to the cordova javascript layer.

**Comment by ddksaku** [comment]
Has the issue been fixed? Any plan on the issue?
